# Generated by Django 4.1.5 on 2023-01-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=30)),
                ('screenSize', models.CharField(max_length=20)),
                ('batteryCapacity', models.CharField(max_length=30)),
                ('CPU', models.CharField(max_length=30)),
                ('sim', models.CharField(max_length=30)),
                ('pic', models.FileField(blank=True, default='media/food.jpg', null=True, upload_to='media/images')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='adminn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('shopName', models.CharField(max_length=30)),
                ('shopAddress', models.CharField(max_length=30)),
                ('pic', models.FileField(default='media/myPic.png', upload_to='media/images')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
